export const KEYWORDS = [
  "investissement",
  "trader",
  "traders",
  "trading",
  "crypto",
  "cryptos",
  "cryptomonnaie",
  "investissements",
  "employement",
  "working online",
  "online work",
  "capital",
  "profit",
  "profits",
  "income",
  "earn",
  "Bitcoin",
  "bitcoin",
  "investi",
  "soup",
  "remove joined group",
  "Message de Test",	
];